# Nome do workflow
name: Build, Push Docker Image and Deploy to Render

# Evento que dispara o workflow: push na branch 'master'
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest # O job será executado em um contêiner Ubuntu

    steps:
    # Passo 1: Fazer checkout do código do repositório
    - name: Checkout code
      uses: actions/checkout@v2

    # Passo 2: Configurar o Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Passo 3: Fazer login no Docker Hub usando segredos armazenados no GitHub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Nome de usuário do Docker Hub
        password: ${{ secrets.DOCKER_PASSWORD }} # Senha do Docker Hub

    # Passo 4: Configurar QEMU para builds multi-plataforma
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # Passo 5: Construir e enviar a imagem Docker para o Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: . # O contexto de build é o diretório atual
        push: true # Enviar a imagem após o build, ${{ github.sha }} Adiciona o SHA do commit na tag
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/apicadastropessoasdockerimage:latest
          ${{ secrets.DOCKER_USERNAME }}/apicadastropessoasdockerimage:${{ github.sha }} 
          

    # Passo 6: Exibir o digest da imagem construída
    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}

    # Passo 7: Fazer deploy da imagem no Render usando a URL de implantação
    - name: Deploy to Render
      run: |
        curl -X POST https://api.render.com/deploy/srv-cpv365tumphs73c4qs90?key=vLbD-ezuTqM
